{% set name = "version_information" %}
{% set version = "1.0.3" %}
{% set md5 = "1fc32b7f0be67fbba2ecdfade40ea116" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - ipython

test:
  imports:
    - version_information

about:
  home: https://github.com/jrjohansson/version_information
  dev_url: https://github.com/jrjohansson/version_information
  license: BSD
  summary: 'Version information for Jupyter notebooks'

extra:
  recipe-maintainers:
    - moorepants
