{% set name = "version_information" %}
{% set version = "1.0.4" %}
{% set md5 = "bc125cc81cf315c658b957ae325039aa" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}
    - ipython

test:
  requires:
    - python {{ python_min }}
  imports:
    - version_information

about:
  home: https://github.com/jrjohansson/version_information
  dev_url: https://github.com/jrjohansson/version_information
  license:  CC-BY-3.0
  summary: Version information for Jupyter notebooks

extra:
  recipe-maintainers:
    - moorepants
