travis:
  secure:
    BINSTAR_TOKEN: e8jZWCmmD0v33dHR+JMfxA0I/MU3DvVLCMmTzByD8LYmG8+bfi0ibxBXmfMjnRIS5GVAZWBCx5YDmaPXF5zmO5D2PKtGfVIar5f9ZD8fIjxvZK1AMKgr2cruo5tDGSTpNp+pzVx94C/BhTwYFjaWSoWHipE2Vz1PKLgMWs4lxqaKbF8u23xWSb7pJiwQRr0CW+JOCr0yvUhiU8PKAQjZWK+pMw+5E7jD3lV8HBiHIgKqicNCULD4TdCO1y285y9nckNrXyjlhpxWTqkkr70iCQKvrGrfJiCV8Cpj7JuavII9XKzs0ErGUNpNXhmujEB+ljjbR4pw/I6rpfgv36uGItVi+CeXsuk/7T7LglOSyJRqf8z6P8+Itkid/zGTF4YUYxBFNi/mpTK+CMWXgMUYHWeZFPb1kPeaeCOAao/3j2O0P/EqayYVzmrMydLWwkBfdRrUMlmKw1KCESBpjdWzjdxt1XSEDsdmZtf7WIwuPV5REM3Hr8DZrP3j+AzfS6M6qeqiv2MrjKCbPvbiFrv2N5UdJIvEaOPX0JSstdX6wuHIGDsNaAeCe/OpqUnL/rK/GJzfUaOoyGGu2L1dGkONSCmANRAcadmSsn83cRlB+iYLnkp53A6MVf/RbFPRqaCy8RhvHitvYfAXNGqgDAiTZy1SLzUqJeI7KUab5bojKEs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
