travis:
  secure:
    BINSTAR_TOKEN: beyS1Cl29iNM+rzqSs6gz07mFbv7r6YOUDuJG+HJQJz7iRht30mKFUjoHQOWiOifj6RoxuCVGhpyKlptINngz3KcbETAb6u4jJ2lQ8bkaILjVrlH6UOOTQCTuRngwzV9p2fcbQlJ+VR/JDToIRwC/Flwyn8KS4KN6HNvv3ag0JiWA7YNNO+juwtmi8ydfn418tx6/AfhWzT2Zywd5hsYUsljLJsAbPcKUSffTkSQY9pA6Q3lsYj5W6p/y0rAP/iWW5DlWqLCEWhw5CvZRPAdIX2vR0fRHX0jVvPJAe3KrzMQIvkV6z9s6tYqqA0uwCgm/rsKpvaa+R53XM2pQuLg5O+fmgENQ7tXs9RsA1fJc/a9x73FlfUIO7tupAUW8JzuejCO/QJc9MxjdazKGN/VtSzvPEwgEjB7tF40taS9EfXamHo638q9/WLkOC65Oz6a/SgLiTcIEr2Zi7WAqOgOs+oh68DPGI7Y9luc9ebJdIU6i+i9yDyx5DmVXdnRuhqqseBWrWcAwZKmNS0CEzkO042JCbY7lF6h9Iy4kpPLQu2YMcbYB91NO38kevlhHHbLC/eTLc5wHpj++3qiBOOrnjIm5jXiPqedGqY1ibGqhEzSW+ytxGdiQ0aHxiZh6vv93eIch4K1CzF491xV8qV6hzLUb172LfFC+eMqP/P407g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
